version: "2"

services:
  ireport:
    build: .
    volumes:
    - $HOME/.ireport:/root/.ireport
    - /tmp/.X11-unix:/tmp/.X11-unix
    - $HOME/reports:/root/reports
    privileged: true
    environment:
      DISPLAY:
