version: "2"

services:
  android-studio:
    build: .
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME:/home/developer
      - $HOME/.AndroidStudio3.0:/developer/.AndroidStudio3.0
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
